Changeable config and automatic download of dictionaries
mbanon/fastspell pull request #10
Opened 2023-01-19 12:10 UTC by ZJaume

Download still has to be implemented, that's why draft.

2023-01-23 15:37 UTC, ZJaume commented
Download is implemented. Default hunspel dictpath in config is now empty, as the code has already a preset of paths to look for them. The first default path, and the one used in download command, is `~/.local/share/fastspell`. Not using `/usr/share` because will need root permissions to download and not using `.local/share/hunspell` because default dictionaries have some customs that I didn't want to interfere with a possible exising hunspell installation.

To test this run:
```
pip install .
fastspell-download
```
and all the dictionaries should be downloaded, so all the `fastspell` commands with similar langs should work out of the box.

README update pending

2023-01-24 09:21 UTC, mbanon requested changes

2023-01-24 09:21 UTC, mbanon commented on README.md
> +Please note that you need Hunspell dictionaries for all the languages in this file (if you use the download command, this is handled for you). This file can be modified to remove a language you are n
Plz reword the "this is handled for you" becase it's confusing.

2023-01-24 09:31 UTC, mbanon approved these changes
thaaanks =^_^=

2023-01-24 10:25 UTC, merged